# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do

FIREBASE_CLI_TOKEN = ENV["FIREBASE_CLI_TOKEN"]


  desc "build app"
  lane :build do
    gradle(task: "clean assembleDebug")
  end

  desc "Submit a new Beta Build to Firebase App Distribution"
  lane :beta do
    build

    firebase_app_distribution(
          app: "1:541840207502:android:a9b547f5e4f0b04f00a3df",
          groups: "qa-team",
          release_notes: "Lots of amazing new features to test out!",
           firebase_cli_token: FIREBASE_CLI_TOKEN
      )
  end

   # Fetch latest build version from Firebase App Distribution and increment version by 1
          desc "Get latest build version from Firebase App Distribution"
          lane :getLatestVersionAndUpgrade do
              latest_release = firebase_app_distribution_get_latest_release(
                app: "1:541840207502:android:a9b547f5e4f0b04f00a3df",
              firebase_cli_token: FIREBASE_CLI_TOKEN
              )
              increment_version_code({ version_code: latest_release[:buildVersion].to_i + 1 })
            end


end
