# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do

FIREBASE_CLI_TOKEN = ENV["FIREBASE_CLI_TOKEN"]


  desc "build app"
  lane :build do
  end

  desc "Submit a new Beta Build to Firebase App Distribution"
  lane :beta do
    #build

    firebase_app_distribution(
          app: "1:541840207502:android:a9b547f5e4f0b04f00a3df",
          groups: "qa-team",
          release_notes: "Lots of amazing new features to test out!",
           firebase_cli_token: FIREBASE_CLI_TOKEN
      )
  end

   # Fetch latest build version from Firebase App Distribution and increment version by 1
          desc "Get latest build version from Firebase App Distribution"
          lane :getLatestVersionAndUpgrade do
              latest_release = firebase_app_distribution_get_latest_release(
                app: "1:541840207502:android:a9b547f5e4f0b04f00a3df",
              firebase_cli_token: FIREBASE_CLI_TOKEN
              )
                print(latest_release)
                UPDATED_VERSION_CODE = latest_release[:buildVersion].to_i + 1
                  print(UPDATED_VERSION_CODE.to_i)
                   android_set_version_code(
                      version_code: UPDATED_VERSION_CODE.to_i, # optional, if not specified, Version Code will be incremented
                      gradle_file: "app/build.gradle.kts" # optional
                    )
#              increment_version_code(
#                  gradle_file_path:"../app/build.gradle",
#                  version_code: UPDATED_VERSION_CODE.to_i
#                )
                #gradle(task: "clean assembleDebug")
                #beta

              #increment_version_code({ version_code: latest_release[:buildVersion].to_i + 1 })
            end


end
