object Versions {
    const val appCompat = "1.5.1"
    const val gradle = "7.1.0"
    const val kotlin = "1.7.10"
    const val coroutines = "1.3.9"
    const val lifecycle = "2.5.1"
    const val fragmentKtx = "2.3.5"
    const val material = "1.6.1"
    const val constraintLayout = "2.1.4"
    const val coreKTX = "1.6.0"
    const val hilt = "2.42"
    const val ANDROID_GRADLE_SPOTLESS = "6.7.0"
    const val hiltViewModel = "1.0.0-alpha03"
    const val retrofit = "2.9.0"
    const val gson = "2.9.0"
    const val loggingInterceptor = "4.9.0"
    const val androidVeil = "1.1.3"
    const val espressoCore = "3.4.0"
    const val jUnit = "4.13.2"
    const val jUnitExt = "1.1.3"
    const val CheckDependencyUpdates = "1.5.0"
    const val navUiKtx = "2.3.5"
    const val navFragment = "2.3.5"
    const val activityKtx = "1.1.0"
}