name: Test and deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  unit_tests:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - name: Unit tests
        run: ./gradlew test

